TOP = ..
include $(TOP)/configure/CONFIG

DIRS += edm
include $(TOP)/configure/RULES_DIRS

ADL_DIR = medm
UI_DIR  = caqtdm/autoconvert
EDL_DIR = edm/autoconvert
OPI_DIR = boy/autoconvert

-include $(SUPPORT)/configure/RULES_OPI